server:
  port: 8081
spring: 
  application:
    name: server-nscer
  profiles:
    active: dev
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/rpctest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: a132135
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true


access: 
  key: zT3QFu2nJLzOQ3GU
  secret: ueDfvMponftzoAFN96myOb6aw3zNmT

app:
  tag: 1.0

eos:
  cloud:
    url: https://developer.yonyoucloud.com/eos-console/
tcc:
  cloud:
    url: https://developer.yonyoucloud.com/eos-console/

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/rpctest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: a132135
  pool:
    minIdle: 5
    maxIdle: 10
    maxActive: 2000
    maxWait: 120000
    minEvictableIdleTimeMillis: 6000
    removeAbandoned: true
    removeAbandonedTimeout: 6000